### PR TITLE
Sdl2

### PR DESCRIPTION
**Pull request by atupone**

### CODE REVIEW

**Comment by macsforme** [comment]
Good idea to add support for SDL 2 without removing support for SDL 1.2. I did a test implementation a bit ago for mac, but it involved a replacement rather than addition. This looks a lot cleaner.

**Comment by macsforme** [comment]
Issues so far are:

1. It needed an ifdef HAVE_SDL_SDL_H in bzfSDL.h so that it properly uses <SDL2/SDL.h> versus "SDL.h"
2. Needed some Xcode project file changes to compile on mac
3. ./configure gives a syntax error when checking the SDL version
4. Toggling fullscreen results in a black screen (at least on mac)
5. Holding down shift while typing doesn't capitalize your letters

I'm working on fixes, but am planning to hold off on merging this in until they are fixed so we still have a usable build in the v2_4_x branch.

**Comment by macsforme** [comment]
This has been merged into the main repo, along with some additional fixes. Thanks for your hard work.

**Comment by JMakey** [comment]
Thanks, both of you, for the contribution.

**Pull request closed without merging**
